import { Platform } from "react-native";

export const Colors = {
  light: {
    text: "#1A2433",
    textSecondary: "#4A5568",
    textTertiary: "#6B7888",
    textOnPrimary: "#FFFFFF",
    textOnAccent: "#FFFFFF",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7888",
    tabIconSelected: "#FF6B2C",
    link: "#1F3650",
    backgroundRoot: "#F5F7FA",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#E8ECF1",
    backgroundTertiary: "#D0D7E0",
    primary: "#1F3650",
    primaryLight: "#2D4A6A",
    primaryDark: "#152538",
    accent: "#FF6B2C",
    accentLight: "#FF8F5C",
    accentDark: "#E55A1F",
    statusIdle: "#7A8694",
    statusOpen: "#5A9BD5",
    statusInProgress: "#2563EB",
    statusCompleted: "#059669",
    statusCancelled: "#DC2626",
    fillLow: "#059669",
    fillMedium: "#D97706",
    fillHigh: "#DC2626",
    fillCritical: "#991B1B",
    border: "#D0D7E0",
    borderLight: "#E8ECF1",
    error: "#DC2626",
    errorLight: "#FEE2E2",
    warning: "#D97706",
    warningLight: "#FEF3C7",
    success: "#059669",
    successLight: "#D1FAE5",
    info: "#2563EB",
    infoLight: "#DBEAFE",
    cardSurface: "#FFFFFF",
    cardBorder: "#E2E8F0",
    cardSurfaceElevated: "#FFFFFF",
    overlay: "rgba(15, 23, 42, 0.5)",
    divider: "#E2E8F0",
  },
  dark: {
    text: "#F1F5F9",
    textSecondary: "#94A3B8",
    textTertiary: "#64748B",
    textOnPrimary: "#FFFFFF",
    textOnAccent: "#FFFFFF",
    buttonText: "#FFFFFF",
    tabIconDefault: "#64748B",
    tabIconSelected: "#FF6B2C",
    link: "#60A5FA",
    backgroundRoot: "#0C1220",
    backgroundDefault: "#131B2B",
    backgroundSecondary: "#1C2638",
    backgroundTertiary: "#263244",
    primary: "#3B6B9C",
    primaryLight: "#5088BC",
    primaryDark: "#1F3650",
    accent: "#FF6B2C",
    accentLight: "#FF8F5C",
    accentDark: "#E55A1F",
    statusIdle: "#64748B",
    statusOpen: "#60A5FA",
    statusInProgress: "#3B82F6",
    statusCompleted: "#10B981",
    statusCancelled: "#EF4444",
    fillLow: "#10B981",
    fillMedium: "#F59E0B",
    fillHigh: "#EF4444",
    fillCritical: "#DC2626",
    border: "#263244",
    borderLight: "#1C2638",
    error: "#EF4444",
    errorLight: "#450A0A",
    warning: "#F59E0B",
    warningLight: "#451A03",
    success: "#10B981",
    successLight: "#052E16",
    info: "#3B82F6",
    infoLight: "#172554",
    cardSurface: "#1C2638",
    cardBorder: "#263244",
    cardSurfaceElevated: "#243040",
    overlay: "rgba(0, 0, 0, 0.7)",
    divider: "#263244",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 52,
  buttonHeight: 56,
  buttonHeightSmall: 48,
  tabBarHeight: 64,
  touchTargetMin: 48,
};

export const BorderRadius = {
  xs: 6,
  sm: 10,
  md: 14,
  lg: 18,
  xl: 22,
  "2xl": 28,
  "3xl": 36,
  full: 9999,
};

export const Typography = {
  h1: {
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 40,
  },
  h2: {
    fontSize: 26,
    fontWeight: "700" as const,
    lineHeight: 34,
  },
  h3: {
    fontSize: 22,
    fontWeight: "600" as const,
    lineHeight: 28,
  },
  h4: {
    fontSize: 18,
    fontWeight: "600" as const,
    lineHeight: 24,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 24,
  },
  bodyBold: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 24,
  },
  small: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
  },
  smallBold: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 20,
  },
  caption: {
    fontSize: 12,
    fontWeight: "500" as const,
    lineHeight: 16,
  },
  captionBold: {
    fontSize: 12,
    fontWeight: "700" as const,
    lineHeight: 16,
  },
  button: {
    fontSize: 15,
    fontWeight: "700" as const,
    letterSpacing: 0.3,
  },
  buttonSmall: {
    fontSize: 13,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
  label: {
    fontSize: 13,
    fontWeight: "600" as const,
    letterSpacing: 0.4,
  },
  link: {
    fontSize: 16,
    fontWeight: "500" as const,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, sans-serif",
    mono: "'SF Mono', SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
  },
});

export const Shadows = {
  none: {
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  small: {
    shadowColor: "#0C1220",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  medium: {
    shadowColor: "#0C1220",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  large: {
    shadowColor: "#0C1220",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 8,
  },
  xl: {
    shadowColor: "#0C1220",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 12,
  },
};

export const IndustrialDesign = {
  minTouchTarget: 48,
  buttonHeight: 56,
  buttonHeightSmall: 48,
  borderWidth: 2,
  borderWidthThin: 1,
  iconSize: 24,
  iconSizeLarge: 28,
  iconSizeXL: 32,
  cardPadding: 16,
  cardPaddingLarge: 20,
  listItemHeight: 72,
  listItemHeightCompact: 56,
  statusBadgeHeight: 28,
  statusBadgePaddingH: 12,
  filterChipHeight: 44,
  headerHeight: 56,
};

export const AnimationConfig = {
  duration: {
    fast: 150,
    normal: 250,
    slow: 400,
  },
  spring: {
    damping: 20,
    stiffness: 300,
    mass: 0.8,
  },
  pressScale: 0.97,
  pressOpacity: 0.85,
};
